### PR TITLE
remove DeprecationWarning for response.buffer #110

### PR DESCRIPTION
**Pull request by lidaof**
Thank you Colin for the response!
I am not sure if this will cause other issues, I was just use this package in my own project, be adjusting the `if` orders removes the warning..

### CODE REVIEW

**Comment by cmdcolin** [comment]
I think with this change, we can probably actually remove the usage of "response.buffer" branch of the if. it is not used in the browser i believe, and i can imagine any impact of changing response.buffer vs arrayBuffer+Buffer.from will only affect some potentially small use case of slightly slower memory copy under node...probably insignificant

**Comment by cmdcolin** [comment]
ill just merge and change on master :) thanks for the contribution

**Comment by lidaof** [comment]
Thank you @cmdcolin !

**Comment by cmdcolin** [comment]
published as v3.1.2 :)

**Pull request merged**
