### PR TITLE
Remove `file://` url monkey patch in `RemoteFile`

### PR DESCRIPTION
**Pull request by manzt**
Since v10.12.0, Node has a builtin `url.fileURLToPath` which seems to accomplish the same thing as `file-uri-to-path`.

The latter npm module has the side-effect of inspecting `process.platform` on import, causing an error when `process` is not defined (e.g. the browser without a polyfill).

### CODE REVIEW

**Comment by cmdcolin** [comment]
I think this should be ok. it is a pretty obscure feature here (monkey patching remotefile into a localfile)...i'm not sure we use it in our apps. it could possibly be considered for deletion

**Comment by manzt** [comment]
> it could possibly be considered for deletion

If it's up for discussion, I think this would be preferred over the solution here. This change would also make it so there are code paths where you are now able to import `RemoteFile` without also needing `LocalFile` implementation.

**Comment by cmdcolin** [comment]
@rbuels any thoughts? I think removing should be ok

**Comment by rbuels** [comment]
Yeah I think that’s fine. Should be a major version bump though.

**Comment by manzt** [comment]
Ok, I updated the PR to remove that block of code in `RemoteFile`. I guess another option would be to move the handling of `file://` url from the `RemoteFile` constructor and delegate to either `RemoteFile` or `LocalFile` in `fromUrl`.

**Comment by cmdcolin** [comment]
I think this should be good! we can try out removing and probably expect or instruct app/consumer code can do fileURLToPath

**Comment by cmdcolin** [comment]
published as 3.0.0!

**Pull request merged**
