### PR TITLE
use `buffer` method on response object if present

### LINKED ISSUE #10: directly use `buffer` method if fetch response supports it
If the response object from fetch has a `buffer` method, use that rather than using arraybuffer and converting back to buffer.

### PR DESCRIPTION
**Pull request by rbuels**
fixes #10

### CODE REVIEW

**Comment by cmdcolin** [comment]
This looks good to me. Definitely agree with the "try harder to determine error"...we have seen two scenarios

1) where CORS produces no status
2) where failing to unzip content produces no status

We should also probably attach some raw information about response status to the error object.

**Comment by cmdcolin** [comment]
I guess I am wondering about the changes to the Buffer copy method

The api says it just returns the number of bytes read

This would return the buffer length from the buffer you pass in which might not correspond to the bytes read

**Comment by rbuels** [comment]
@cmdcolin good point. i changed the number of bytes read to be the number of bytes returned from the buffer.copy command, which I think should be correct.  what do you think about that?

**Comment by cmdcolin** [comment]
That looks good. I added an extra little test for this on this branch

**Pull request merged**
