### PR TITLE
Make a separate server bundle

### PR DESCRIPTION
**Pull request by garrettjstevens**
This is an alternative to #85, which didn't work in a Next.js build. Instead of conditionally importing `fs`, it builds two separate bundles, a node bundle and a browser bundle. The browser bundle does not export LocalFile.

This uses a library called [preconstruct](https://preconstruct.tools/) to build the package. It supports multiple entrypoints and uses Rollup under the hood to build the bundles. I had to `patch-package` it a little to suppress a couple errors that didn't apply to this use case, but creating our own Rollup config is sufficiently complicated that I think using `patch-package` is much simpler.

The RemoteFile in the browser vs. node bundles is slightly different, too. The browser version no longer contains the code that converts `file://` urls to LocalFiles.

I've tested this and it works in a simple node script, a Create React App app and a Next.js app.

### CODE REVIEW

**Comment by cmdcolin** [comment]
thanks for looking into this. some questions

why is preconstruct used? it says it is geared towards monorepos. 

what is meant by multiple entrypoints?

from what I know, I don't really think it should be needed to use a bundler to output our files. bundlers are something that are used to output to the browser, and node is fine with packages containing multiple files.

**Comment by garrettjstevens** [comment]
Ok, after learning a bit more about the standard ways of doing this, I think the way I had it before wasn't quite right. Having an export that exists in node but doesn't exist in the browser isn't a common pattern, and is probably not as useful. The new solution is described below, but it's much more in line with what preconstruct expects, so I was able to remove the `patch-package` patches.

> why is preconstruct used? it says it is geared towards monorepos.

That's the tagline, but it does more than that as well. From their key features, things that are relevant to us include:

- Add multiple entrypoints to your packages for publishing
- Also works for single package repos!

> what is meant by multiple entrypoints?

The idea is that you can import things from multiple places in your package. From preconstruct's docs:

> The most common reason is if you have some client side code and some server side code and you don't want users to pay the cost of loading that server side code or the server side code depends on some modules which aren't available for the browser.

One example is `react-dom` that has a client-side entrypoint at `react-dom` and a server-side entrypoint at `react-dom/server`, so the same package is used in both places, but clients avoid having to deal with the node-only modules.

Following that same pattern, I've updated it so there are now two entrypoints, `generic-filehandle` and `generic-filehandle/server`. Both entrypoints export the same things except:
- `open` and `fromUrl` `generic-filehandle/server` can handle `file://` urls
- LocalFile is exported from `generic-filehandle/server`, but not `generic-filehandle`

> why use a bundler?

Bundlers (like rollup used by preconstruct) aren't just for bundling code for the browser. They can be used for any application or library. With this bundler, we actually get two different bundles, a cjs bundle that is used for node, and an esm bundle, which is specified with the "module" field in the package.json. When e.g. Webpack consumes a library, it actually prefers an esm bundle.

**Comment by cmdcolin** [comment]
>With this bundler, we actually get two different bundles, a cjs bundle that is used for node, and an esm bundle, which is specified with the "module" field in the package.json. When e.g. Webpack consumes a library, it actually prefers an esm bundle.


I am not necessarily convinced we need a bundler for this.

for example, for esm, the babel could be configured to not rewrite imports, it does not need to use a bundler to do this

**Comment by cmdcolin** [comment]
I think probably #88 was a helpful alternative to this, can probably close for now

**Pull request closed without merging**
