### PR TITLE
Add test for passing authorization token through remoteFile

### PR DESCRIPTION
**Pull request by cmdcolin**
This attempts to allow people to override headers

The way that the code existed was that the headers would be "clobbered" by the spread. This makes it so that the override headers are merged more properly

### CODE REVIEW

**Comment by cmdcolin** [comment]
Usage of this for example could be like so

```
var headers = {
  Authorization: "**",
};
const remoteTbiIndexed = new TabixIndexedFile({
  filehandle: new RemoteFile(url_template, {
    fetch,
    headers: { Authorization: "*****" },
  }),
  tbiFilehandle: new RemoteFile(tbi_url_template, {
    fetch,
    headers: { Authorization: "*****" },
  }),
});
```

**Comment by rbuels** [comment]
nice.

**Comment by rbuels** [comment]
do you want me to release to npm or you wanna do it

**Comment by cmdcolin** [comment]
I think it might worth testing with a couple of our modules....we could release it and iterate on it but it would be good to confirm it works in practice

**Comment by cmdcolin** [comment]
well. actually I think it's probably fine.. the tests at least cover the case of supplying a authorization token to the constructor well. I'll go ahead and release and we can iterate if needed

**Pull request merged**
