### PR TITLE
convert repo to use tsdx

### PR DESCRIPTION
**Pull request by rbuels**
This PR converts the dev tooling to be based on tsdx, to hopefully standardize its type exporting etc

### CODE REVIEW

**Comment by cmdcolin** [comment]
what do you mean "standardize its type exporting"? IMO tsdx contains some cruft in it. I prefer to stick with the plain build tools if possible

**Comment by rbuels** [comment]
just wasn't getting types exported well into trix-js, which matt was using. nevermind though, i don't have more time to spend on this

**Comment by cmdcolin** [comment]
I see. sorry if that is troubling.... happy to help if i can though

**Comment by cmdcolin** [comment]
See my comment on  #75  too...I am curious what is causing the perceived type issues

**Pull request closed without merging**
